### PR TITLE
Port ContractExecutionResult

### PR DESCRIPTION
**Pull request by supl**
This PR adds a class ContractExecutionResult.

It's the port of https://github.com/scalar-labs/scalardl-javascript-sdk-base/blob/master/contract_execution_result.js

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by feeblefakie** [comment]
@supl Sorry, there is a conflict. Please resolve it and then merge when you get a chance!

**Comment by supl** [comment]
> @supl Sorry, there is a conflict. Please resolve it and then merge when you get a chance!

@feeblefakie 
Thank you!
I resolved the conflict!

**Review by ypeckstadt — APPROVED** [review]
LGTM. Thank you.

**Review by jnmt — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
